### ISSUE TITLE
Create a website that allows to display 'biologic' data

### ISSUE THREAD

**Issue by lpatiny** [zakodium-oss/galvanicium#1]
On the home page we have basic information about how to use 'galvanicium'

The following path allows to drag / drop biologic files (or '.ium' files)

This kind of URL should work:

https://app.galvanicium.org/#?filelist=https://zakodium-oss.github.io/analysis-dataset/biologic.json

**Comment by targos** [comment]
@lpatiny have you already published urls like this somewhere? I'd like to put the app under `https://app.galvanicium.org`.

**Comment by lpatiny** [comment]
No
